import type { Metadata } from "next";
import { Ubuntu } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import BackToTopButton from "@/components/backToTop/BackToTop";

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
  variable: '--font-ubuntu',     
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon-2.png'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ubuntu.className}
      >
        <Navbar />
        {children}
        <BackToTopButton />
      </body>
    </html>
  );
}
